---
author: G. Conway
date: May 7, 2020
output: 
    pdf_document: default
    word_document: default
---

```{r setwd, echo=FALSE, include=FALSE}
setwd("~/Desktop/kid school work stuff")
```

```{r load_pkgs, echo=FALSE, include=FALSE}
library(tidyverse)
library(readxl)
library(kableExtra)
```

```{r get_data, echo=FALSE, include=FALSE}
words <- read_xlsx("Spelling & Sight words 1st grade.xlsx")
```

```{r keep_relevant_cols, echo=FALSE, include=FALSE}
spelling_words <- words$`Spelling Words`

sight_words <- words$`Sight Words`

rm(words)

spelling_words <- spelling_words[!is.na(spelling_words)]

sight_words <- sight_words[!is.na(sight_words)]
```

```{r set_seed, echo=FALSE, include=FALSE}
set.seed(413)
```

```{r create_new_df, echo=FALSE, include=FALSE}
# repeat sight words to go with length of spelling words list
sight_words <- rep(sight_words, 4)

# drop 3 random sight words to make vector length the same
sight_words <- sight_words[-sample(1:length(sight_words), 3, replace = F)]

# create new data frame
newdf <- as.data.frame(cbind(spelling_words, sight_words))

newdf <- newdf[-which(duplicated(spelling_words)), ]
```

```{r echo=FALSE, include=FALSE}
# randomize the indices
indices <- sample(1:681, 681, replace = F)

newdf <- newdf[indices, ]
```

```{r assign_words, echo=FALSE, include=FALSE}
assign("week1", newdf[1:85, ])
assign("week2", newdf[86:170, ])
assign("week3", newdf[171:255, ])
assign("week4", newdf[256:340, ])
assign("week5", newdf[341:425, ])
assign("week6", newdf[426:510, ])
assign("week7", newdf[511:595, ])
assign("week8", newdf[596:681, ])

# clean memory
rm(indices, sight_words, spelling_words)
```

# Week 1

```{r week1, echo=F}
kable(week1, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```

\newpage  

# Week 2

```{r week2, echo=F}
kable(week2, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```

\newpage  

# Week 3

```{r week3, echo=F}
kable(week3, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```

\newpage  

# Week 4

```{r week4, echo=F}
kable(week4, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```

\newpage  

# Week 5

```{r week5, echo=F}
kable(week5, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```

\newpage  

# Week 6

```{r week6, echo=F}
kable(week6, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```

\newpage  

# Week 7

```{r week7, echo=F}
kable(week7, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```

\newpage  

# Week 8

```{r week8, echo=F}
kable(week8, "latex", longtable = T, booktabs = T, row.names = F) %>%
    kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = "20em") %>%
    group_rows("Monday", 1, 17, latex_gap_space = "2em") %>%
    group_rows("Tuesday", 18, 34, latex_gap_space = "2em") %>%
    group_rows("Wednesday", 35, 51, latex_gap_space = "2em") %>%
    group_rows("Thursday", 52, 63, latex_gap_space = "2em") %>%
    group_rows("Friday", 64, 85, latex_gap_space = "2em")
```